baseURL = "https://priceless-mcclintock-83b64f.netlify.app"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

languageCode = "en-us"
defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The "title" of your website
title = "Makers Magnet ðŸ§² - Where Makers Meet"

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "Â© Makers Magnet ðŸ§²"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Makers Magnet ðŸ§²"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/cover-image.png"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Makers Magnet ðŸ§² - Where Makers Meet"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you donâ€™t :-)
    # hidedesignbyline = true

    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
